import { ArrowPathIcon, ClockIcon, EllipsisVerticalIcon, KeyIcon, PencilSquareIcon, ShieldCheckIcon, UserGroupIcon } from '@heroicons/react/24/outline';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState, useEffect, useRef } from 'react';
import { useForm } from 'react-hook-form';
import { useTranslation } from 'react-i18next';
import { Navigate } from 'react-router-dom';

import { Modal } from '../../components/Modal';
import { useAuthStore } from '../../contexts/useAuthStore';
import api from '../../services/apiClient';

interface UserForm {
  fullName: string;
  email?: string;
  department?: string;
  jobTitle?: string;
  role: string;
  supervisorId?: string;
  useAutoGeneratedLogin: boolean;
}

interface PasswordResetForm {
  temporaryPassword: string;
}

// Password generator function
function generateTemporaryPassword(length = 12): string {
  const charset = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*';
  const array = new Uint32Array(length);
  crypto.getRandomValues(array);
  return Array.from(array)
    .map((value) => charset[value % charset.length])
    .join('');
}

export default function AdminPage() {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const user = useAuthStore((state) => state.user);
  const [isEditOpen, setEditOpen] = useState(false);
  const [isPasswordResetOpen, setPasswordResetOpen] = useState(false);
  const [editingUser, setEditingUser] = useState<any>(null);
  const [resetPasswordUser, setResetPasswordUser] = useState<any>(null);
  const [generatedPassword, setGeneratedPassword] = useState('');
  const [openActionMenuId, setOpenActionMenuId] = useState<string | null>(null);
  const actionMenuRefs = useRef<{ [key: string]: HTMLDivElement | null }>({});
  const [searchQuery, setSearchQuery] = useState('');
  
  const { register, handleSubmit, reset, watch, setValue } = useForm<UserForm>();
  const { register: registerPassword, handleSubmit: handleSubmitPassword, reset: resetPassword, setValue: setPasswordValue } = useForm<PasswordResetForm>();

  // Check if user has admin access
  if (!user || (user.role !== 'global_admin' && user.role !== 'admin')) {
    return <Navigate to="/app/dashboard" replace />;
  }

  // Fetch all users
  const { data: users = [], isLoading } = useQuery({
    queryKey: ['admin-users'],
    queryFn: async () => {
      const response = await api.get('/users');
      return response.data;
    }
  });

  // Fetch supervisors
  const { data: supervisors = [] } = useQuery({
    queryKey: ['supervisors'],
    queryFn: async () => {
      const response = await api.get('/users/supervisors');
      return response.data;
    }
  });

  // Update user mutation
  const updateUserMutation = useMutation({
    mutationFn: async ({ id, data }: { id: string; data: any }) => {
      const response = await api.put(`/users/${id}`, data);
      return response.data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['admin-users'] });
      reset();
      setEditOpen(false);
      setEditingUser(null);
      alert('User updated successfully!');
    },
    onError: (error: any) => {
      alert(`Error updating user: ${error.response?.data?.message || error.message}`);
    }
  });

  // Reset password mutation
  const resetPasswordMutation = useMutation({
    mutationFn: async ({ userId, newPassword }: { userId: string; newPassword: string }) => {
      const response = await api.post(`/users/${userId}/reset-password`, { newPassword });
      return response.data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['admin-users'] });
      alert('Password reset successfully! Make sure to share the new password with the user.');
      setPasswordResetOpen(false);
      setResetPasswordUser(null);
      setGeneratedPassword('');
      resetPassword();
    },
    onError: (error: any) => {
      alert(`Error resetting password: ${error.response?.data?.message || error.message}`);
    }
  });

  const useAutoGeneratedLogin = watch('useAutoGeneratedLogin');

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      Object.values(actionMenuRefs.current).forEach((ref) => {
        if (ref && !ref.contains(event.target as Node)) {
          setOpenActionMenuId(null);
        }
      });
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, []);

  const handleEdit = (userToEdit: any) => {
    setEditingUser(userToEdit);
    setValue('fullName', userToEdit.full_name);
    setValue('email', userToEdit.email || '');
    setValue('department', userToEdit.department || '');
    setValue('jobTitle', userToEdit.job_title || '');
    setValue('role', userToEdit.role);
    setValue('supervisorId', userToEdit.supervisor_id || '');
    setValue('useAutoGeneratedLogin', !userToEdit.email);
    setOpenActionMenuId(null);
    setEditOpen(true);
  };

  const handleUpdate = (data: UserForm) => {
    if (!editingUser) return;
    
    updateUserMutation.mutate({
      id: editingUser.id,
      data: {
        fullName: data.fullName,
        email: data.useAutoGeneratedLogin ? undefined : data.email,
        department: data.department,
        jobTitle: data.jobTitle,
        role: data.role,
        supervisorId: data.supervisorId
      }
    });
  };

  const handlePasswordReset = (userToReset: any) => {
    setResetPasswordUser(userToReset);
    const newPassword = generateTemporaryPassword();
    setGeneratedPassword(newPassword);
    setPasswordValue('temporaryPassword', newPassword);
    setOpenActionMenuId(null);
    setPasswordResetOpen(true);
  };

  const handleRegeneratePassword = () => {
    const newPassword = generateTemporaryPassword();
    setGeneratedPassword(newPassword);
    setPasswordValue('temporaryPassword', newPassword);
  };

  const handleSubmitPasswordReset = (data: PasswordResetForm) => {
    if (!resetPasswordUser) return;
    resetPasswordMutation.mutate({
      userId: resetPasswordUser.id,
      newPassword: data.temporaryPassword
    });
  };

  const filteredUsers = users.filter((u: any) => {
    if (!searchQuery) return true;
    const query = searchQuery.toLowerCase();
    return (
      u.full_name?.toLowerCase().includes(query) ||
      u.email?.toLowerCase().includes(query) ||
      u.employee_id?.toLowerCase().includes(query) ||
      u.department?.toLowerCase().includes(query) ||
      u.role?.toLowerCase().includes(query)
    );
  });

  const stats = [
    { title: t('totalUsers'), value: String(users.length), accent: 'bg-blue-100 text-blue-600 dark:bg-blue-500/10 dark:text-blue-200' },
    { title: t('activeUsers'), value: String(users.filter((u: any) => u.status === 'active').length), accent: 'bg-emerald-100 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-200' },
    { title: t('administrators'), value: String(users.filter((u: any) => ['global_admin', 'admin'].includes(u.role)).length), accent: 'bg-purple-100 text-purple-600 dark:bg-purple-500/10 dark:text-purple-200' },
    { title: t('employees'), value: String(users.filter((u: any) => u.role === 'employee').length), accent: 'bg-orange-100 text-orange-600 dark:bg-orange-500/10 dark:text-orange-200' }
  ];

  return (
    <div className="space-y-6">
      <header>
        <h1 className="text-3xl font-bold text-slate-900 dark:text-white">
          <ShieldCheckIcon className="mb-1 inline-block h-8 w-8 mr-2" />
          {t('administration')}
        </h1>
        <p className="mt-1 text-sm text-slate-600 dark:text-slate-400">
          Manage all users, update details, and reset passwords
        </p>
      </header>

      {/* Stats Cards */}
      <section className="grid gap-6 sm:grid-cols-2 xl:grid-cols-4">
        {stats.map((stat) => (
          <div key={stat.title} className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
            <div className="flex items-center justify-between">
              <p className="text-sm font-medium text-slate-600 dark:text-slate-400">{stat.title}</p>
              <UserGroupIcon className={`h-5 w-5 ${stat.accent.split(' ')[1]}`} />
            </div>
            <p className="mt-3 text-3xl font-bold text-slate-900 dark:text-white">{stat.value}</p>
          </div>
        ))}
      </section>

      {/* User Management Section */}
      <div className="rounded-2xl border border-slate-100 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <div className="border-b border-slate-200 px-6 py-4 dark:border-slate-700">
          <div className="flex items-center justify-between gap-4">
            <div>
              <h2 className="text-lg font-semibold text-slate-900 dark:text-white">
                <UserGroupIcon className="mb-1 inline-block h-5 w-5 mr-2" />
                {t('userManagement') || 'User Management'}
              </h2>
              <p className="text-sm text-slate-500 dark:text-slate-300">
                View and manage all users across the system
              </p>
            </div>
            <input
              type="text"
              placeholder={t('searchUsers') || 'Search users...'}
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
            />
          </div>
        </div>

        <div className="p-6">
          <div className="overflow-x-auto overflow-y-visible rounded-2xl border border-slate-100 dark:border-slate-800">
            <table className="min-w-full divide-y divide-slate-100 dark:divide-slate-800">
              <thead className="bg-slate-50 dark:bg-slate-800/60">
                <tr>
                  {[t('user'), t('department'), t('jobTitle'), t('role'), t('status'), t('joined'), t('actions')].map((header) => (
                    <th key={header} className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-300">
                      {header}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 bg-white dark:divide-slate-800 dark:bg-slate-900">
                {isLoading ? (
                  <tr>
                    <td colSpan={7} className="px-6 py-12 text-center text-sm text-slate-500 dark:text-slate-400">
                      {t('loading') || 'Loading users...'}
                    </td>
                  </tr>
                ) : filteredUsers.length === 0 ? (
                  <tr>
                    <td colSpan={7} className="px-6 py-12 text-center text-sm text-slate-500 dark:text-slate-400">
                      {searchQuery ? (t('noUsersFound') || 'No users found matching your search.') : (t('noUsers') || 'No users found.')}
                    </td>
                  </tr>
                ) : (
                  filteredUsers.map((userItem: any) => (
                    <tr key={userItem.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/50">
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-3">
                          <div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10 text-primary font-semibold">
                            {userItem.full_name?.[0]?.toUpperCase() || 'U'}
                          </div>
                          <div>
                            <p className="text-sm font-semibold text-slate-900 dark:text-white">
                              {userItem.full_name}
                            </p>
                            <p className="text-xs text-slate-500 dark:text-slate-400">
                              {userItem.email || userItem.employee_id || 'No email'}
                            </p>
                          </div>
                        </div>
                      </td>
                      <td className="px-6 py-4 text-sm text-slate-600 dark:text-slate-300">
                        {userItem.department || t('unassigned')}
                      </td>
                      <td className="px-6 py-4 text-sm text-slate-600 dark:text-slate-300">
                        {userItem.job_title || '—'}
                      </td>
                      <td className="px-6 py-4">
                        <span className="inline-flex rounded-full bg-purple-100 px-2.5 py-0.5 text-xs font-semibold text-purple-600 dark:bg-purple-500/10 dark:text-purple-200">
                          {userItem.role?.replace('_', ' ')}
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        <span
                          className={`inline-flex rounded-full px-2.5 py-0.5 text-xs font-semibold ${
                            userItem.status === 'active'
                              ? 'bg-emerald-100 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-200'
                              : 'bg-red-100 text-red-600 dark:bg-red-500/10 dark:text-red-200'
                          }`}
                        >
                          {userItem.status === 'active' ? (t('active') || 'Active') : (t('inactive') || 'Inactive')}
                        </span>
                      </td>
                      <td className="px-6 py-4 text-sm text-slate-500 dark:text-slate-400">
                        {userItem.joined_date ? new Date(userItem.joined_date).toLocaleDateString() : '—'}
                      </td>
                      <td className="px-6 py-4">
                        <div className="relative" ref={(el) => (actionMenuRefs.current[userItem.id] = el)}>
                          <button
                            onClick={() => setOpenActionMenuId(openActionMenuId === userItem.id ? null : userItem.id)}
                            className="rounded-lg p-2 text-slate-600 transition hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800"
                          >
                            <EllipsisVerticalIcon className="h-5 w-5" />
                          </button>
                          {openActionMenuId === userItem.id && (
                            <div className="absolute right-0 z-[100] mt-2 w-56 rounded-xl border border-slate-200 bg-white shadow-xl dark:border-slate-700 dark:bg-slate-800">
                              <div className="py-1">
                                <button
                                  onClick={() => handleEdit(userItem)}
                                  className="flex w-full items-center gap-2 px-4 py-2 text-sm text-slate-700 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-700"
                                >
                                  <PencilSquareIcon className="h-4 w-4" />
                                  {t('editUser') || 'Edit User'}
                                </button>
                                <button
                                  onClick={() => handlePasswordReset(userItem)}
                                  className="flex w-full items-center gap-2 px-4 py-2 text-sm text-slate-700 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-700"
                                >
                                  <KeyIcon className="h-4 w-4" />
                                  {t('resetPassword') || 'Reset Password'}
                                </button>
                              </div>
                            </div>
                          )}
                        </div>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>


      {/* Edit User Modal */}
      <Modal
        open={isEditOpen}
        onClose={() => {
          setEditOpen(false);
          setEditingUser(null);
          reset();
        }}
        title={t('editUser') || 'Edit User'}
        description={t('updateUserDetails') || 'Update user details and permissions'}
      >
        <form onSubmit={handleSubmit(handleUpdate)} className="space-y-6">
          <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 dark:border-blue-500/40 dark:bg-blue-500/10">
            <label className="flex items-start gap-3">
              <input
                type="checkbox"
                {...register('useAutoGeneratedLogin')}
                className="mt-0.5 h-4 w-4 rounded border-slate-300 text-primary focus:ring-primary"
              />
              <div>
                <span className="text-sm font-semibold text-blue-900 dark:text-blue-100">
                  {t('workerWithoutEmail')}
                </span>
                <p className="mt-1 text-xs text-blue-700 dark:text-blue-200">
                  {t('autoGeneratedLoginDesc')}
                </p>
              </div>
            </label>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                {t('fullName')} *
              </label>
              <input
                type="text"
                {...register('fullName', { required: true })}
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
              />
            </div>

            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                {t('emailAddress')} {!useAutoGeneratedLogin && '*'}
              </label>
              <input
                type="email"
                {...register('email', { required: !useAutoGeneratedLogin })}
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                disabled={useAutoGeneratedLogin}
              />
            </div>

            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                {t('department')} *
              </label>
              <select
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                {...register('department', { required: true })}
              >
                <option value="">{t('selectDepartment')}</option>
                <option value="operations">{t('operations')}</option>
                <option value="maintenance">{t('maintenance')}</option>
                <option value="quality">{t('quality')}</option>
                <option value="administration">{t('administration')}</option>
              </select>
            </div>

            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                {t('jobTitle')} *
              </label>
              <select
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                {...register('jobTitle', { required: true })}
              >
                <option value="">{t('selectJobTitle')}</option>
                <option value="technician">Technician</option>
                <option value="operator">Operator</option>
                <option value="supervisor">Supervisor</option>
                <option value="manager">Manager</option>
              </select>
            </div>

            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                {t('initialRole')} *
              </label>
              <select
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                {...register('role', { required: true })}
              >
                <option value="employee">{t('employee')}</option>
                <option value="supervisor">{t('supervisor')}</option>
                <option value="manager">{t('manager')}</option>
                <option value="admin">{t('admin')}</option>
                <option value="global_admin">{t('globalAdmin')}</option>
              </select>
            </div>

            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                {t('assignedSupervisor')}
              </label>
              <select
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                {...register('supervisorId')}
              >
                <option value="">{t('selectSupervisor')}</option>
                {supervisors.map((sup: any) => (
                  <option key={sup.id} value={sup.id}>
                    {sup.full_name || sup.fullName}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div className="flex items-center justify-end gap-3 border-t border-slate-200 pt-4 dark:border-slate-700">
            <button
              type="button"
              onClick={() => {
                setEditOpen(false);
                setEditingUser(null);
                reset();
              }}
              className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-medium text-slate-600 hover:border-primary hover:text-primary dark:border-slate-700 dark:text-slate-300"
            >
              {t('cancel')}
            </button>
            <button
              type="submit"
              className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-primary/90"
            >
              {t('updateUser') || 'Update User'}
            </button>
          </div>
        </form>
      </Modal>

      {/* Password Reset Modal */}
      <Modal
        open={isPasswordResetOpen}
        onClose={() => {
          setPasswordResetOpen(false);
          setResetPasswordUser(null);
          setGeneratedPassword('');
          resetPassword();
        }}
        title={t('resetPassword') || 'Reset Password'}
        description={`${t('generateTemporaryPassword') || 'Generate a temporary password for'} ${resetPasswordUser?.full_name || 'user'}`}
      >
        <form onSubmit={handleSubmitPassword(handleSubmitPasswordReset)} className="space-y-6">
          <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 dark:border-amber-500/40 dark:bg-amber-500/10">
            <p className="text-sm font-semibold text-amber-900 dark:text-amber-100">
              🔐 {t('important') || 'Important'}
            </p>
            <p className="mt-1 text-xs text-amber-700 dark:text-amber-200">
              {t('sharePasswordSecurely') || 'Make sure to securely share this temporary password with the user. They should change it upon first login.'}
            </p>
          </div>

          <div>
            <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
              {t('temporaryPassword') || 'Temporary Password'}
            </label>
            <div className="flex gap-2">
              <input
                type="text"
                {...registerPassword('temporaryPassword', { required: true })}
                className="flex-1 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100 font-mono"
                readOnly
              />
              <button
                type="button"
                onClick={handleRegeneratePassword}
                className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700 transition hover:border-primary hover:text-primary dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300"
              >
                <ArrowPathIcon className="h-4 w-4" />
                {t('regenerate') || 'Regenerate'}
              </button>
            </div>
            <p className="mt-2 text-xs text-slate-500 dark:text-slate-400">
              {t('clickRegenerateNewPassword') || 'Click "Regenerate" to create a new random password if you don\'t like this one.'}
            </p>
          </div>

          <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 dark:border-blue-500/40 dark:bg-blue-500/10">
            <p className="text-sm font-semibold text-blue-900 dark:text-blue-100">
              📋 {t('copyPassword') || 'Copy Password'}
            </p>
            <p className="mt-1 text-xs text-blue-700 dark:text-blue-200">
              {t('copyPasswordInstruction') || 'Select and copy the password above before submitting. You won\'t be able to see it again.'}
            </p>
          </div>

          <div className="flex items-center justify-end gap-3 border-t border-slate-200 pt-4 dark:border-slate-700">
            <button
              type="button"
              onClick={() => {
                setPasswordResetOpen(false);
                setResetPasswordUser(null);
                setGeneratedPassword('');
                resetPassword();
              }}
              className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-medium text-slate-600 hover:border-primary hover:text-primary dark:border-slate-700 dark:text-slate-300"
            >
              {t('cancel')}
            </button>
            <button
              type="submit"
              className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-primary/90"
            >
              {t('resetPassword') || 'Reset Password'}
            </button>
          </div>
        </form>
      </Modal>
    </div>
  );
}
