import { ArrowDownTrayIcon, DocumentArrowUpIcon, DocumentMagnifyingGlassIcon, EllipsisVerticalIcon, InformationCircleIcon, PencilSquareIcon, PlusIcon, PowerIcon } from '@heroicons/react/24/outline';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState, useMemo, useEffect, useRef } from 'react';
import { useForm } from 'react-hook-form';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';

import { EmployeeInfoModal } from '../../components/EmployeeInfoModal';
import { Modal } from '../../components/Modal';
import { StatsCard } from '../../components/StatsCard';
import api from '../../services/apiClient';

interface InviteForm {
  useAutoGeneratedLogin: boolean;
  fullName: string;
  email?: string;
  department?: string;
  jobTitle?: string;
  role: string;
  supervisorId?: string;
  joinedDate?: string;
  personalMessage?: string;
}

export default function UserManagementPage() {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const navigate = useNavigate();
  const [isInviteOpen, setInviteOpen] = useState(false);
  const [isEditOpen, setEditOpen] = useState(false);
  const [isImportOpen, setImportOpen] = useState(false);
  const [isEmployeeInfoOpen, setEmployeeInfoOpen] = useState(false);
  const [csvFile, setCsvFile] = useState<File | null>(null);
  const [editingUser, setEditingUser] = useState<any>(null);
  const [createdEmployee, setCreatedEmployee] = useState<any>(null);
  const [openActionMenuId, setOpenActionMenuId] = useState<string | null>(null);
  const [showFormerEmployees, setShowFormerEmployees] = useState(false);
  const actionMenuRefs = useRef<{ [key: string]: HTMLDivElement | null }>({});
  
  const { register, handleSubmit, reset, watch, setValue } = useForm<InviteForm>({
    defaultValues: {
      useAutoGeneratedLogin: false,
      role: 'employee',
      joinedDate: new Date().toISOString().split('T')[0]
    }
  });

  // Fetch users
  const { data: users = [], isLoading } = useQuery({
    queryKey: ['users'],
    queryFn: async () => {
      const response = await api.get('/users');
      return response.data;
    }
  });

  // Fetch supervisors
  const { data: supervisors = [] } = useQuery({
    queryKey: ['supervisors'],
    queryFn: async () => {
      const response = await api.get('/users/supervisors');
      return response.data;
    }
  });

  // Create user mutation
  const createUserMutation = useMutation({
    mutationFn: async (userData: any) => {
      const response = await api.post('/users', userData);
      return response.data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['users'] });
      reset();
      setInviteOpen(false);
      setCreatedEmployee(data);
      setEmployeeInfoOpen(true);
    },
    onError: (error: any) => {
      alert(`Error creating user: ${error.response?.data?.message || error.message}`);
    }
  });

  // Update user mutation
  const updateUserMutation = useMutation({
    mutationFn: async ({ id, data }: { id: string; data: any }) => {
      const response = await api.put(`/users/${id}`, data);
      return response.data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['users'] });
      reset();
      setEditOpen(false);
      setEditingUser(null);
      alert('User updated successfully!');
    },
    onError: (error: any) => {
      alert(`Error updating user: ${error.response?.data?.message || error.message}`);
    }
  });

  const toggleUserStatusMutation = useMutation({
    mutationFn: async ({ id, isActive }: { id: string; isActive: boolean }) => {
      const response = await api.patch(`/users/${id}/status`, { isActive });
      return response.data;
    },
    onMutate: async (variables) => {
      await queryClient.cancelQueries({ queryKey: ['users'] });
      const previousUsers = queryClient.getQueryData<any[]>(['users']);

      queryClient.setQueryData(['users'], (old: any[] = []) =>
        old.map((user) =>
          user.id === variables.id
            ? { ...user, isActive: variables.isActive, status: variables.isActive ? 'active' : 'inactive' }
            : user
        )
      );

      return { previousUsers };
    },
    onError: (error: any, _variables, context) => {
      if (context?.previousUsers) {
        queryClient.setQueryData(['users'], context.previousUsers);
      }
      alert(`Error updating user status: ${error.response?.data?.message || error.message}`);
    },
    onSettled: () => {
      queryClient.invalidateQueries({ queryKey: ['users'] });
      setOpenActionMenuId(null);
    }
  });

  const stats = [
    { title: t('totalUsers'), value: String(users.length), accent: 'bg-blue-100 text-blue-600 dark:bg-blue-500/10 dark:text-blue-200' },
    { title: t('activeUsers'), value: String(users.filter((u: any) => u.status === 'active').length), accent: 'bg-emerald-100 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-200' },
    { title: t('administrators'), value: String(users.filter((u: any) => ['global_admin', 'admin'].includes(u.role)).length), accent: 'bg-purple-100 text-purple-600 dark:bg-purple-500/10 dark:text-purple-200' },
    { title: t('employees'), value: String(users.filter((u: any) => u.role === 'employee').length), accent: 'bg-orange-100 text-orange-600 dark:bg-orange-500/10 dark:text-orange-200' }
  ];

  const useAutoGeneratedLogin = watch('useAutoGeneratedLogin');
  const fullName = watch('fullName');

  // Generate email preview for auto-generated login
  const emailPreview = useMemo(() => {
    if (!useAutoGeneratedLogin || !fullName || fullName.trim().length === 0) {
      return '';
    }

    const names = fullName.trim().split(/\s+/);
    let initials = '';
    
    if (names.length >= 2) {
      initials = (names[0][0] || '') + (names[names.length - 1][0] || '');
    } else if (names.length === 1 && names[0].length >= 2) {
      initials = (names[0][0] || '') + (names[0][1] || '');
    } else {
      initials = 'XX';
    }

    // We don't know the exact employee number yet, so show placeholder
    return `${initials.toUpperCase()}EMPXXX@complete-pet.com`.toLowerCase();
  }, [useAutoGeneratedLogin, fullName]);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      Object.values(actionMenuRefs.current).forEach((ref) => {
        if (ref && !ref.contains(event.target as Node)) {
          setOpenActionMenuId(null);
        }
      });
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, []);

  const handleInvite = (data: InviteForm) => {
    createUserMutation.mutate({
      fullName: data.fullName,
      email: data.useAutoGeneratedLogin ? undefined : data.email,
      department: data.department,
      jobTitle: data.jobTitle,
      role: data.role,
      supervisorId: data.supervisorId,
      joinedDate: data.joinedDate
    });
  };

  const handleEdit = (user: any) => {
    setEditingUser(user);
    setValue('fullName', user.full_name);
    setValue('email', user.email || '');
    setValue('department', user.department || '');
    setValue('jobTitle', user.job_title || '');
    setValue('role', user.role);
    setValue('supervisorId', user.supervisor_id || '');
    setValue('useAutoGeneratedLogin', !user.email);
    setOpenActionMenuId(null);
    setEditOpen(true);
  };

  const handleUpdate = (data: InviteForm) => {
    if (!editingUser) return;
    
    updateUserMutation.mutate({
      id: editingUser.id,
      data: {
        fullName: data.fullName,
        email: data.useAutoGeneratedLogin ? undefined : data.email,
        department: data.department,
        jobTitle: data.jobTitle,
        role: data.role,
        supervisorId: data.supervisorId
      }
    });
  };

  const handleToggleStatus = (user: any) => {
    const currentStatus = user.isActive ?? (user.status === 'active');
    toggleUserStatusMutation.mutate({
      id: user.id,
      isActive: !currentStatus
    });
  };

  const handleToggleFormerEmployees = () => {
    setShowFormerEmployees(!showFormerEmployees);
  };

  // Filter users based on former employees toggle
  const filteredUsers = showFormerEmployees 
    ? users.filter((u: any) => {
        const isActive = u.isActive ?? (u.status === 'active');
        return !isActive;
      })
    : users.filter((u: any) => {
        const isActive = u.isActive ?? (u.status === 'active');
        return isActive;
      });

  const handleViewActivity = (user: any) => {
    setOpenActionMenuId(null);
    navigate(`/app/users/${user.id}/activity`);
  };

  const handleCSVUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setCsvFile(e.target.files[0]);
    }
  };

  const handleImport = () => {
    if (csvFile) {
      console.log('Import CSV', csvFile);
      setCsvFile(null);
      setImportOpen(false);
    }
  };

  return (
    <div className="space-y-10">
      <header className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-semibold text-slate-900 dark:text-white">{t('userManagementTitle')}</h1>
          <p className="text-sm text-slate-500 dark:text-slate-300">{t('userManagementSubtitle')}</p>
        </div>
        <div className="flex flex-wrap gap-3">
          <button
            onClick={() => setImportOpen(true)}
            className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700 transition hover:border-primary hover:text-primary dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300"
          >
            <DocumentArrowUpIcon className="h-5 w-5" />
            {t('bulkImportCSV')}
          </button>
          <button
            onClick={() => setInviteOpen(true)}
            className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-primary/90"
          >
            <PlusIcon className="h-5 w-5" />
            {t('inviteUserEmail')}
          </button>
        </div>
      </header>

      {/* How to Add Users Info Banner */}
      <section className="rounded-xl border border-blue-200 bg-blue-50 p-6 dark:border-blue-500/40 dark:bg-blue-500/10">
        <div className="flex items-start gap-3">
          <InformationCircleIcon className="h-6 w-6 shrink-0 text-blue-600 dark:text-blue-400" />
          <div className="space-y-3 text-sm text-blue-900 dark:text-blue-100">
            <h3 className="font-semibold">{t('howToAddUsers')}</h3>
            <div className="space-y-2">
              <p>
                <span className="font-semibold">{t('bulkImportCSV')}:</span>{' '}
                {t('bulkImportDesc')}
              </p>
              <p>
                <span className="font-semibold">{t('inviteUserEmail')}:</span>{' '}
                {t('inviteUserDesc')}
              </p>
              <p className="text-xs italic">
                After the account is created, <strong>only Global Administrators</strong> can edit the employee's department, position, and other profile details. Regular users cannot change these fields themselves.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="grid gap-6 sm:grid-cols-2 xl:grid-cols-4">
        {stats.map((card) => (
          <StatsCard key={card.title} {...card} />
        ))}
      </section>

      <section className="rounded-3xl border border-slate-100 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <h2 className="text-lg font-semibold text-slate-900 dark:text-white">{t('userDirectory')}</h2>
            <p className="text-sm text-slate-500 dark:text-slate-300">Search and filter users for the current location.</p>
          </div>
          <div className="flex gap-2">
            <button className="rounded-xl border border-slate-200 px-4 py-2 text-sm text-slate-600 hover:border-primary hover:text-primary dark:border-slate-700 dark:text-slate-300">
              {t('exportCSV')}
            </button>
            <button 
              onClick={handleToggleFormerEmployees}
              className={`rounded-xl border px-4 py-2 text-sm font-medium transition ${
                showFormerEmployees
                  ? 'border-primary bg-primary text-white'
                  : 'border-slate-200 text-slate-600 hover:border-primary hover:text-primary dark:border-slate-700 dark:text-slate-300'
              }`}
            >
              {t('formerEmployees')}
            </button>
          </div>
        </div>

        <input
          type="text"
          placeholder={t('searchUsers')}
          className="mt-4 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-2 text-sm outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
        />

        <div className="mt-6 overflow-x-auto overflow-y-visible rounded-2xl border border-slate-100 dark:border-slate-800">
          <table className="min-w-full divide-y divide-slate-100 dark:divide-slate-800">
            <thead className="bg-slate-50 dark:bg-slate-800/60">
              <tr>
                {[t('user'), t('department'), t('role'), t('enrollments'), t('status'), t('joined'), t('actions')].map((header) => (
                  <th key={header} className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-300">
                    {header}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 bg-white dark:divide-slate-800 dark:bg-slate-900">
              {isLoading ? (
                <tr>
                  <td colSpan={7} className="px-6 py-12 text-center text-sm text-slate-500 dark:text-slate-400">
                    Loading users...
                  </td>
                </tr>
              ) : filteredUsers.length === 0 ? (
                <tr>
                  <td colSpan={7} className="px-6 py-12 text-center text-sm text-slate-500 dark:text-slate-400">
                    {showFormerEmployees 
                      ? (t('noFormerEmployees') || 'No former employees found.')
                      : (t('noUsers') || 'No users found. Create your first user above.')
                    }
                  </td>
                </tr>
              ) : (
                filteredUsers.map((user: any) => (
                  <tr key={user.id}>
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-3">
                        <div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10 text-primary font-semibold">
                          {user.full_name?.[0]?.toUpperCase() || 'U'}
                        </div>
                        <div>
                          <p className="text-sm font-semibold text-slate-900 dark:text-white">
                            {user.employee_id || user.full_name}
                          </p>
                          <p className="text-xs text-slate-500 dark:text-slate-400">
                            {user.email || 'No email'}
                          </p>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-sm text-slate-600 dark:text-slate-300">
                      {user.department || t('unassigned')}
                    </td>
                    <td className="px-6 py-4">
                      <span className="inline-flex rounded-full bg-purple-100 px-2.5 py-0.5 text-xs font-semibold text-purple-600 dark:bg-purple-500/10 dark:text-purple-200">
                        {user.role?.replace('_', ' ')}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-sm text-slate-600 dark:text-slate-300">
                      0 {t('assigned')} · 0 {t('completed')}
                    </td>
                    <td className="px-6 py-4">
                      <span
                        className={`inline-flex rounded-full px-2.5 py-0.5 text-xs font-semibold ${
                          (user.isActive ?? (user.status === 'active'))
                            ? 'bg-emerald-100 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-200'
                            : 'bg-red-100 text-red-600 dark:bg-red-500/10 dark:text-red-200'
                        }`}
                      >
                        {(user.isActive ?? (user.status === 'active')) ? (t('active') || 'Active') : (t('inactive') || 'Inactive')}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-sm text-slate-500 dark:text-slate-400">
                      {user.joined_date ? new Date(user.joined_date).toLocaleDateString() : '—'}
                    </td>
                    <td className="px-6 py-4">
                      <div className="relative" ref={(el) => (actionMenuRefs.current[user.id] = el)}>
                        <button
                          onClick={() => setOpenActionMenuId(openActionMenuId === user.id ? null : user.id)}
                          className="rounded-lg p-2 text-slate-600 transition hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800"
                        >
                          <EllipsisVerticalIcon className="h-5 w-5" />
                        </button>
                        {openActionMenuId === user.id && (
                          <div className="absolute right-0 z-[100] mt-2 w-56 rounded-xl border border-slate-200 bg-white shadow-xl dark:border-slate-700 dark:bg-slate-800">
                            <div className="py-1">
                              <button
                                onClick={() => handleEdit(user)}
                                className="flex w-full items-center gap-2 px-4 py-2 text-sm text-slate-700 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-700"
                              >
                                <PencilSquareIcon className="h-4 w-4" />
                                {t('update') || 'Update'}
                              </button>
                              <button
                                onClick={() => handleToggleStatus(user)}
                                className="flex w-full items-center gap-2 px-4 py-2 text-sm text-slate-700 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-700"
                              >
                                <PowerIcon className={`h-4 w-4 ${(user.isActive ?? (user.status === 'active')) ? 'text-red-500' : 'text-emerald-500'}`} />
                                {(user.isActive ?? (user.status === 'active')) ? (t('deactivate') || 'Deactivate') : (t('reactivate') || 'Reactivate')}
                              </button>
                              <button
                                onClick={() => handleViewActivity(user)}
                                className="flex w-full items-center gap-2 px-4 py-2 text-sm text-slate-700 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-700"
                              >
                                <DocumentMagnifyingGlassIcon className="h-4 w-4" />
                                {t('viewActivityLog') || 'View activity log'}
                              </button>
                            </div>
                          </div>
                        )}
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </section>

      {/* Create Employee Access Modal */}
      <Modal
        open={isInviteOpen}
        onClose={() => {
          setInviteOpen(false);
          reset();
        }}
        title={t('createEmployeeAccess')}
        description={t('generateLoginCredentials')}
      >
        <form className="space-y-6" onSubmit={handleSubmit(handleInvite)}>
          {/* Auto-generated login checkbox */}
          <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 dark:border-blue-500/40 dark:bg-blue-500/10">
            <label className="flex items-start gap-3">
              <input
                type="checkbox"
                {...register('useAutoGeneratedLogin')}
                className="mt-0.5 h-4 w-4 rounded border-slate-300 text-primary focus:ring-primary"
              />
              <div>
                <span className="text-sm font-semibold text-blue-900 dark:text-blue-100">
                  {t('workerWithoutEmail')}
                </span>
                <p className="mt-1 text-xs text-blue-700 dark:text-blue-200">
                  {t('autoGeneratedLoginDesc')}
                </p>
              </div>
            </label>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                {t('fullName')} *
              </label>
              <input
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                {...register('fullName', { required: true })}
                placeholder="John Doe"
              />
            </div>

            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                {t('emailAddress')} {!useAutoGeneratedLogin && '*'}
              </label>
              <input
                type="email"
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                {...register('email', { required: !useAutoGeneratedLogin })}
                placeholder="john@complete-pet.com"
                disabled={useAutoGeneratedLogin}
                value={useAutoGeneratedLogin ? emailPreview : undefined}
                readOnly={useAutoGeneratedLogin}
              />
              {useAutoGeneratedLogin && emailPreview && (
                <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
                  Preview: Actual employee number will be assigned upon creation
                </p>
              )}
            </div>

            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                {t('department')} *
              </label>
              <select
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                {...register('department', { required: true })}
              >
                <option value="">{t('selectDepartment')}</option>
                <option value="operations">{t('operations')}</option>
                <option value="maintenance">{t('maintenance')}</option>
                <option value="quality">{t('quality')}</option>
                <option value="administration">{t('administration')}</option>
              </select>
            </div>

            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                {t('jobTitle')} *
              </label>
              <select
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                {...register('jobTitle', { required: true })}
              >
                <option value="">{t('selectJobTitle')}</option>
                <option value="technician">Technician</option>
                <option value="operator">Operator</option>
                <option value="supervisor">Supervisor</option>
                <option value="manager">Manager</option>
              </select>
            </div>

            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                {t('initialRole')} *
              </label>
              <select
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                {...register('role', { required: true })}
              >
                <option value="employee">{t('employee')}</option>
                <option value="supervisor">{t('supervisor')}</option>
                <option value="manager">{t('manager')}</option>
                <option value="admin">{t('admin')}</option>
                <option value="global_admin">{t('globalAdmin')}</option>
              </select>
            </div>

            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                {t('assignedSupervisor')} *
              </label>
              <select
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                {...register('supervisorId')}
              >
                <option value="">{t('selectSupervisor')}</option>
                {supervisors.map((sup: any) => (
                  <option key={sup.id} value={sup.id}>
                    {sup.full_name || sup.fullName}
                  </option>
                ))}
              </select>
              <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{t('selectSupervisorDesc')}</p>
            </div>

            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                Joined Date
              </label>
              <input
                type="date"
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                {...register('joinedDate')}
              />
              <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
                Employee's start date (only Global Admin can edit)
              </p>
            </div>
          </div>

          <div>
            <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
              {t('personalMessage')}
            </label>
            <textarea
              rows={3}
              className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
              {...register('personalMessage')}
              placeholder={t('addPersonalWelcome')}
            />
          </div>

          {/* Important box */}
          <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 dark:border-amber-500/40 dark:bg-amber-500/10">
            <p className="text-sm font-semibold text-amber-900 dark:text-amber-100">⚠️ {t('important')}</p>
            <p className="mt-1 text-xs text-amber-700 dark:text-amber-200">
              {t('credentialsSharedManually')}
            </p>
          </div>

          {/* Auto-enrollment box */}
          <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 dark:border-emerald-500/40 dark:bg-emerald-500/10">
            <p className="text-sm font-semibold text-emerald-900 dark:text-emerald-100">🎓 {t('autoEnrollment')}</p>
            <p className="mt-1 text-xs text-emerald-700 dark:text-emerald-200">
              {t('autoEnrollmentDesc')}
            </p>
          </div>

          <div className="flex items-center justify-end gap-3 border-t border-slate-200 pt-4 dark:border-slate-700">
            <button
              type="button"
              onClick={() => {
                setInviteOpen(false);
                reset();
              }}
              className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-medium text-slate-600 hover:border-primary hover:text-primary dark:border-slate-700 dark:text-slate-300"
            >
              {t('cancel')}
            </button>
            <button 
              type="submit" 
              className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-primary/90"
            >
              {t('createEmployeeBtn')}
            </button>
          </div>
        </form>
      </Modal>

      {/* Bulk Import Modal */}
      <Modal
        open={isImportOpen}
        onClose={() => {
          setImportOpen(false);
          setCsvFile(null);
        }}
        title={t('bulkUserImport')}
        description={t('importMultipleUsers')}
      >
        <div className="space-y-6">
          {/* CSV Format Requirements */}
          <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 dark:border-blue-500/40 dark:bg-blue-500/10">
            <p className="text-sm font-semibold text-blue-900 dark:text-blue-100">📋 {t('csvFormatRequirements')}</p>
            <ul className="mt-2 space-y-1 text-xs text-blue-700 dark:text-blue-200">
              <li>• {t('requiredColumns')}</li>
              <li>• {t('optionalColumns')}</li>
              <li>• {t('employeeIdAutoGenerated')}</li>
              <li>• {t('supervisorEmailRequired')}</li>
              <li>• {t('noEmailProvided')}</li>
            </ul>
          </div>

          {/* Download Template Button */}
          <button className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700 transition hover:border-primary hover:text-primary dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300">
            <ArrowDownTrayIcon className="h-5 w-5" />
            {t('downloadTemplate')}
          </button>

          {/* Upload Area */}
          <div>
            <p className="mb-3 text-sm font-semibold text-slate-900 dark:text-white">{t('uploadCSVFile')}</p>
            <label className="flex cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 p-12 transition hover:border-primary hover:bg-slate-100 dark:border-slate-700 dark:bg-slate-800 dark:hover:border-primary dark:hover:bg-slate-700">
              <DocumentArrowUpIcon className="h-12 w-12 text-slate-400 dark:text-slate-500" />
              <p className="mt-3 text-sm font-medium text-slate-700 dark:text-slate-300">
                {csvFile ? csvFile.name : t('clickToBrowse')}
              </p>
              <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
                {t('chooseFile')}
              </p>
              <input
                type="file"
                accept=".csv"
                onChange={handleCSVUpload}
                className="hidden"
              />
            </label>
          </div>

          <div className="flex items-center justify-end gap-3 border-t border-slate-200 pt-4 dark:border-slate-700">
            <button
              type="button"
              onClick={() => {
                setImportOpen(false);
                setCsvFile(null);
              }}
              className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-medium text-slate-600 hover:border-primary hover:text-primary dark:border-slate-700 dark:text-slate-300"
            >
              {t('cancel')}
            </button>
            <button
              onClick={handleImport}
              disabled={!csvFile}
              className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-primary/90 disabled:opacity-50"
            >
              {t('bulkUserImport')}
            </button>
          </div>
        </div>
      </Modal>

      {/* Employee Info Modal */}
      {createdEmployee && (
        <EmployeeInfoModal
          open={isEmployeeInfoOpen}
          onClose={() => {
            setEmployeeInfoOpen(false);
            setCreatedEmployee(null);
          }}
          employeeData={{
            fullName: createdEmployee.fullName,
            employeeId: createdEmployee.employeeId,
            email: createdEmployee.loginIdentifier,
            department: createdEmployee.department,
            jobTitle: createdEmployee.jobTitle,
            role: createdEmployee.role,
            temporaryPassword: createdEmployee.temporaryPassword
          }}
        />
      )}

      {/* Edit User Modal */}
      <Modal
        open={isEditOpen}
        onClose={() => {
          setEditOpen(false);
          setEditingUser(null);
          reset();
        }}
        title={t('editUser') || 'Edit User'}
        description={t('updateUserDetails') || 'Update user details and permissions'}
      >
        <form onSubmit={handleSubmit(handleUpdate)} className="space-y-6">
          <div className="space-y-4">
            {/* Same form fields as Create User */}
            <div className="rounded-lg border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-800">
              <label className="flex items-center gap-2">
                <input
                  type="checkbox"
                  {...register('useAutoGeneratedLogin')}
                  className="h-4 w-4 rounded border-slate-300 text-primary focus:ring-primary dark:border-slate-600 dark:bg-slate-700"
                />
                <span className="text-sm font-medium text-slate-700 dark:text-slate-200">
                  {t('workerWithoutEmail')}
                </span>
              </label>
              <p className="mt-2 text-xs text-slate-500 dark:text-slate-400">
                {t('autoGeneratedLoginDesc')}
              </p>
            </div>

            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                {t('fullName')} *
              </label>
              <input
                type="text"
                {...register('fullName', { required: true })}
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
              />
            </div>

            {!useAutoGeneratedLogin && (
              <div>
                <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                  {t('emailAddress')} *
                </label>
                <input
                  type="email"
                  {...register('email', { required: !useAutoGeneratedLogin })}
                  className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                />
              </div>
            )}

            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                {t('department')} *
              </label>
              <select
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                {...register('department', { required: true })}
              >
                <option value="">{t('selectDepartment')}</option>
                <option value="operations">Operations</option>
                <option value="maintenance">Maintenance</option>
                <option value="quality">Quality Control</option>
                <option value="administration">Administration</option>
              </select>
            </div>

            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                {t('jobTitle')} *
              </label>
              <select
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                {...register('jobTitle', { required: true })}
              >
                <option value="">{t('selectJobTitle')}</option>
                <option value="technician">Technician</option>
                <option value="operator">Operator</option>
                <option value="supervisor">Supervisor</option>
                <option value="manager">Manager</option>
              </select>
            </div>

            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                {t('initialRole')} *
              </label>
              <select
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                {...register('role', { required: true })}
              >
                <option value="employee">{t('employee')}</option>
                <option value="supervisor">{t('supervisor')}</option>
                <option value="manager">{t('manager')}</option>
                <option value="admin">{t('admin')}</option>
                <option value="global_admin">{t('globalAdmin')}</option>
              </select>
            </div>

            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200">
                {t('assignedSupervisor')} *
              </label>
              <select
                className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                {...register('supervisorId')}
              >
                <option value="">{t('selectSupervisor')}</option>
                {supervisors.map((sup: any) => (
                  <option key={sup.id} value={sup.id}>
                    {sup.full_name || sup.fullName}
                  </option>
                ))}
              </select>
              <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{t('selectSupervisorDesc')}</p>
            </div>
          </div>

          <div className="flex items-center justify-end gap-3 border-t border-slate-200 pt-4 dark:border-slate-700">
            <button
              type="button"
              onClick={() => {
                setEditOpen(false);
                setEditingUser(null);
                reset();
              }}
              className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-medium text-slate-600 hover:border-primary hover:text-primary dark:border-slate-700 dark:text-slate-300"
            >
              {t('cancel')}
            </button>
            <button
              type="submit"
              className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-primary/90"
            >
              {t('updateUser') || 'Update User'}
            </button>
          </div>
        </form>
      </Modal>
    </div>
  );
}
