import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowDownTrayIcon, DocumentArrowUpIcon, DocumentMagnifyingGlassIcon, EllipsisVerticalIcon, InformationCircleIcon, PencilSquareIcon, PlusIcon, PowerIcon } from '@heroicons/react/24/outline';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState, useMemo, useEffect, useRef } from 'react';
import { useForm } from 'react-hook-form';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { EmployeeInfoModal } from '../../components/EmployeeInfoModal';
import { Modal } from '../../components/Modal';
import { StatsCard } from '../../components/StatsCard';
import api from '../../services/apiClient';
export default function UserManagementPage() {
    const { t } = useTranslation();
    const queryClient = useQueryClient();
    const navigate = useNavigate();
    const [isInviteOpen, setInviteOpen] = useState(false);
    const [isEditOpen, setEditOpen] = useState(false);
    const [isImportOpen, setImportOpen] = useState(false);
    const [isEmployeeInfoOpen, setEmployeeInfoOpen] = useState(false);
    const [csvFile, setCsvFile] = useState(null);
    const [editingUser, setEditingUser] = useState(null);
    const [createdEmployee, setCreatedEmployee] = useState(null);
    const [openActionMenuId, setOpenActionMenuId] = useState(null);
    const actionMenuRefs = useRef({});
    const { register, handleSubmit, reset, watch, setValue } = useForm({
        defaultValues: {
            useAutoGeneratedLogin: false,
            role: 'employee',
            joinedDate: new Date().toISOString().split('T')[0]
        }
    });
    // Fetch users
    const { data: users = [], isLoading } = useQuery({
        queryKey: ['users'],
        queryFn: async () => {
            const response = await api.get('/users');
            return response.data;
        }
    });
    // Fetch supervisors
    const { data: supervisors = [] } = useQuery({
        queryKey: ['supervisors'],
        queryFn: async () => {
            const response = await api.get('/users/supervisors');
            return response.data;
        }
    });
    // Create user mutation
    const createUserMutation = useMutation({
        mutationFn: async (userData) => {
            const response = await api.post('/users', userData);
            return response.data;
        },
        onSuccess: (data) => {
            queryClient.invalidateQueries({ queryKey: ['users'] });
            reset();
            setInviteOpen(false);
            setCreatedEmployee(data);
            setEmployeeInfoOpen(true);
        },
        onError: (error) => {
            alert(`Error creating user: ${error.response?.data?.message || error.message}`);
        }
    });
    // Update user mutation
    const updateUserMutation = useMutation({
        mutationFn: async ({ id, data }) => {
            const response = await api.put(`/users/${id}`, data);
            return response.data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['users'] });
            reset();
            setEditOpen(false);
            setEditingUser(null);
            alert('User updated successfully!');
        },
        onError: (error) => {
            alert(`Error updating user: ${error.response?.data?.message || error.message}`);
        }
    });
    const toggleUserStatusMutation = useMutation({
        mutationFn: async ({ id, isActive }) => {
            const response = await api.patch(`/users/${id}/status`, { isActive });
            return response.data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['users'] });
            setOpenActionMenuId(null);
        },
        onError: (error) => {
            alert(`Error updating user status: ${error.response?.data?.message || error.message}`);
        }
    });
    const stats = [
        { title: t('totalUsers'), value: String(users.length), accent: 'bg-blue-100 text-blue-600 dark:bg-blue-500/10 dark:text-blue-200' },
        { title: t('activeUsers'), value: String(users.filter((u) => u.status === 'active').length), accent: 'bg-emerald-100 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-200' },
        { title: t('administrators'), value: String(users.filter((u) => ['global_admin', 'admin'].includes(u.role)).length), accent: 'bg-purple-100 text-purple-600 dark:bg-purple-500/10 dark:text-purple-200' },
        { title: t('employees'), value: String(users.filter((u) => u.role === 'employee').length), accent: 'bg-orange-100 text-orange-600 dark:bg-orange-500/10 dark:text-orange-200' }
    ];
    const useAutoGeneratedLogin = watch('useAutoGeneratedLogin');
    const fullName = watch('fullName');
    // Generate email preview for auto-generated login
    const emailPreview = useMemo(() => {
        if (!useAutoGeneratedLogin || !fullName || fullName.trim().length === 0) {
            return '';
        }
        const names = fullName.trim().split(/\s+/);
        let initials = '';
        if (names.length >= 2) {
            initials = (names[0][0] || '') + (names[names.length - 1][0] || '');
        }
        else if (names.length === 1 && names[0].length >= 2) {
            initials = (names[0][0] || '') + (names[0][1] || '');
        }
        else {
            initials = 'XX';
        }
        // We don't know the exact employee number yet, so show placeholder
        return `${initials.toUpperCase()}EMPXXX@complete-pet.com`.toLowerCase();
    }, [useAutoGeneratedLogin, fullName]);
    useEffect(() => {
        const handleClickOutside = (event) => {
            Object.values(actionMenuRefs.current).forEach((ref) => {
                if (ref && !ref.contains(event.target)) {
                    setOpenActionMenuId(null);
                }
            });
        };
        document.addEventListener('mousedown', handleClickOutside);
        return () => {
            document.removeEventListener('mousedown', handleClickOutside);
        };
    }, []);
    const handleInvite = (data) => {
        createUserMutation.mutate({
            fullName: data.fullName,
            email: data.useAutoGeneratedLogin ? undefined : data.email,
            department: data.department,
            jobTitle: data.jobTitle,
            role: data.role,
            supervisorId: data.supervisorId,
            joinedDate: data.joinedDate
        });
    };
    const handleEdit = (user) => {
        setEditingUser(user);
        setValue('fullName', user.full_name);
        setValue('email', user.email || '');
        setValue('department', user.department || '');
        setValue('jobTitle', user.job_title || '');
        setValue('role', user.role);
        setValue('supervisorId', user.supervisor_id || '');
        setValue('useAutoGeneratedLogin', !user.email);
        setOpenActionMenuId(null);
        setEditOpen(true);
    };
    const handleUpdate = (data) => {
        if (!editingUser)
            return;
        updateUserMutation.mutate({
            id: editingUser.id,
            data: {
                fullName: data.fullName,
                email: data.useAutoGeneratedLogin ? undefined : data.email,
                department: data.department,
                jobTitle: data.jobTitle,
                role: data.role,
                supervisorId: data.supervisorId
            }
        });
    };
    const handleToggleStatus = (user) => {
        toggleUserStatusMutation.mutate({
            id: user.id,
            isActive: !user.isActive
        });
    };
    const handleViewActivity = (user) => {
        setOpenActionMenuId(null);
        navigate(`/app/users/${user.id}/activity`);
    };
    const handleCSVUpload = (e) => {
        if (e.target.files && e.target.files[0]) {
            setCsvFile(e.target.files[0]);
        }
    };
    const handleImport = () => {
        if (csvFile) {
            console.log('Import CSV', csvFile);
            setCsvFile(null);
            setImportOpen(false);
        }
    };
    return (_jsxs("div", { className: "space-y-10", children: [_jsxs("header", { className: "flex flex-wrap items-center justify-between gap-4", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-semibold text-slate-900 dark:text-white", children: t('userManagementTitle') }), _jsx("p", { className: "text-sm text-slate-500 dark:text-slate-300", children: t('userManagementSubtitle') })] }), _jsxs("div", { className: "flex flex-wrap gap-3", children: [_jsxs("button", { onClick: () => setImportOpen(true), className: "inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700 transition hover:border-primary hover:text-primary dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300", children: [_jsx(DocumentArrowUpIcon, { className: "h-5 w-5" }), t('bulkImportCSV')] }), _jsxs("button", { onClick: () => setInviteOpen(true), className: "inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-primary/90", children: [_jsx(PlusIcon, { className: "h-5 w-5" }), t('inviteUserEmail')] })] })] }), _jsx("section", { className: "rounded-xl border border-blue-200 bg-blue-50 p-6 dark:border-blue-500/40 dark:bg-blue-500/10", children: _jsxs("div", { className: "flex items-start gap-3", children: [_jsx(InformationCircleIcon, { className: "h-6 w-6 shrink-0 text-blue-600 dark:text-blue-400" }), _jsxs("div", { className: "space-y-3 text-sm text-blue-900 dark:text-blue-100", children: [_jsx("h3", { className: "font-semibold", children: t('howToAddUsers') }), _jsxs("div", { className: "space-y-2", children: [_jsxs("p", { children: [_jsxs("span", { className: "font-semibold", children: [t('bulkImportCSV'), ":"] }), ' ', t('bulkImportDesc')] }), _jsxs("p", { children: [_jsxs("span", { className: "font-semibold", children: [t('inviteUserEmail'), ":"] }), ' ', t('inviteUserDesc')] }), _jsxs("p", { className: "text-xs italic", children: ["After the account is created, ", _jsx("strong", { children: "only Global Administrators" }), " can edit the employee's department, position, and other profile details. Regular users cannot change these fields themselves."] })] })] })] }) }), _jsx("section", { className: "grid gap-6 sm:grid-cols-2 xl:grid-cols-4", children: stats.map((card) => (_jsx(StatsCard, { ...card }, card.title))) }), _jsxs("section", { className: "rounded-3xl border border-slate-100 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-4", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-lg font-semibold text-slate-900 dark:text-white", children: t('userDirectory') }), _jsx("p", { className: "text-sm text-slate-500 dark:text-slate-300", children: "Search and filter users for the current location." })] }), _jsxs("div", { className: "flex gap-2", children: [_jsx("button", { className: "rounded-xl border border-slate-200 px-4 py-2 text-sm text-slate-600 hover:border-primary hover:text-primary dark:border-slate-700 dark:text-slate-300", children: t('exportCSV') }), _jsx("button", { className: "rounded-xl border border-slate-200 px-4 py-2 text-sm text-slate-600 hover:border-primary hover:text-primary dark:border-slate-700 dark:text-slate-300", children: t('formerEmployees') })] })] }), _jsx("input", { type: "text", placeholder: t('searchUsers'), className: "mt-4 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-2 text-sm outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100" }), _jsx("div", { className: "mt-6 overflow-hidden rounded-2xl border border-slate-100 dark:border-slate-800", children: _jsxs("table", { className: "min-w-full divide-y divide-slate-100 dark:divide-slate-800", children: [_jsx("thead", { className: "bg-slate-50 dark:bg-slate-800/60", children: _jsx("tr", { children: [t('user'), t('department'), t('role'), t('enrollments'), t('status'), t('joined'), t('actions')].map((header) => (_jsx("th", { className: "px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-300", children: header }, header))) }) }), _jsx("tbody", { className: "divide-y divide-slate-100 bg-white dark:divide-slate-800 dark:bg-slate-900", children: isLoading ? (_jsx("tr", { children: _jsx("td", { colSpan: 7, className: "px-6 py-12 text-center text-sm text-slate-500 dark:text-slate-400", children: "Loading users..." }) })) : users.length === 0 ? (_jsx("tr", { children: _jsx("td", { colSpan: 7, className: "px-6 py-12 text-center text-sm text-slate-500 dark:text-slate-400", children: "No users found. Create your first user above." }) })) : (users.map((user) => (_jsxs("tr", { children: [_jsx("td", { className: "px-6 py-4", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "flex h-10 w-10 items-center justify-center rounded-full bg-primary/10 text-primary font-semibold", children: user.full_name?.[0]?.toUpperCase() || 'U' }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-semibold text-slate-900 dark:text-white", children: user.employee_id || user.full_name }), _jsx("p", { className: "text-xs text-slate-500 dark:text-slate-400", children: user.email || 'No email' })] })] }) }), _jsx("td", { className: "px-6 py-4 text-sm text-slate-600 dark:text-slate-300", children: user.department || t('unassigned') }), _jsx("td", { className: "px-6 py-4", children: _jsx("span", { className: "inline-flex rounded-full bg-purple-100 px-2.5 py-0.5 text-xs font-semibold text-purple-600 dark:bg-purple-500/10 dark:text-purple-200", children: user.role?.replace('_', ' ') }) }), _jsxs("td", { className: "px-6 py-4 text-sm text-slate-600 dark:text-slate-300", children: ["0 ", t('assigned'), " \u00B7 0 ", t('completed')] }), _jsx("td", { className: "px-6 py-4", children: _jsx("span", { className: `inline-flex rounded-full px-2.5 py-0.5 text-xs font-semibold ${user.status === 'active'
                                                        ? 'bg-emerald-100 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-200'
                                                        : 'bg-red-100 text-red-600 dark:bg-red-500/10 dark:text-red-200'}`, children: user.status === 'active' ? (t('active') || 'Active') : (t('inactive') || 'Inactive') }) }), _jsx("td", { className: "px-6 py-4 text-sm text-slate-500 dark:text-slate-400", children: user.joined_date ? new Date(user.joined_date).toLocaleDateString() : '—' }), _jsx("td", { className: "px-6 py-4", children: _jsxs("div", { className: "relative", ref: (el) => (actionMenuRefs.current[user.id] = el), children: [_jsx("button", { onClick: () => setOpenActionMenuId(openActionMenuId === user.id ? null : user.id), className: "rounded-lg p-2 text-slate-600 transition hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800", children: _jsx(EllipsisVerticalIcon, { className: "h-5 w-5" }) }), openActionMenuId === user.id && (_jsx("div", { className: "absolute right-0 z-50 mt-2 w-56 rounded-xl border border-slate-200 bg-white shadow-xl dark:border-slate-700 dark:bg-slate-800", children: _jsxs("div", { className: "py-1", children: [_jsxs("button", { onClick: () => handleEdit(user), className: "flex w-full items-center gap-2 px-4 py-2 text-sm text-slate-700 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-700", children: [_jsx(PencilSquareIcon, { className: "h-4 w-4" }), t('update') || 'Update'] }), _jsxs("button", { onClick: () => handleToggleStatus(user), className: "flex w-full items-center gap-2 px-4 py-2 text-sm text-slate-700 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-700", children: [_jsx(PowerIcon, { className: `h-4 w-4 ${user.status === 'active' ? 'text-red-500' : 'text-emerald-500'}` }), user.status === 'active' ? (t('deactivate') || 'Deactivate') : (t('reactivate') || 'Reactivate')] }), _jsxs("button", { onClick: () => handleViewActivity(user), className: "flex w-full items-center gap-2 px-4 py-2 text-sm text-slate-700 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-700", children: [_jsx(DocumentMagnifyingGlassIcon, { className: "h-4 w-4" }), t('viewActivityLog') || 'View activity log'] })] }) }))] }) })] }, user.id)))) })] }) })] }), _jsx(Modal, { open: isInviteOpen, onClose: () => {
                    setInviteOpen(false);
                    reset();
                }, title: t('createEmployeeAccess'), description: t('generateLoginCredentials'), children: _jsxs("form", { className: "space-y-6", onSubmit: handleSubmit(handleInvite), children: [_jsx("div", { className: "rounded-xl border border-blue-200 bg-blue-50 p-4 dark:border-blue-500/40 dark:bg-blue-500/10", children: _jsxs("label", { className: "flex items-start gap-3", children: [_jsx("input", { type: "checkbox", ...register('useAutoGeneratedLogin'), className: "mt-0.5 h-4 w-4 rounded border-slate-300 text-primary focus:ring-primary" }), _jsxs("div", { children: [_jsx("span", { className: "text-sm font-semibold text-blue-900 dark:text-blue-100", children: t('workerWithoutEmail') }), _jsx("p", { className: "mt-1 text-xs text-blue-700 dark:text-blue-200", children: t('autoGeneratedLoginDesc') })] })] }) }), _jsxs("div", { className: "grid gap-4 sm:grid-cols-2", children: [_jsxs("div", { children: [_jsxs("label", { className: "mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200", children: [t('fullName'), " *"] }), _jsx("input", { className: "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100", ...register('fullName', { required: true }), placeholder: "John Doe" })] }), _jsxs("div", { children: [_jsxs("label", { className: "mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200", children: [t('emailAddress'), " ", !useAutoGeneratedLogin && '*'] }), _jsx("input", { type: "email", className: "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100", ...register('email', { required: !useAutoGeneratedLogin }), placeholder: "john@complete-pet.com", disabled: useAutoGeneratedLogin, value: useAutoGeneratedLogin ? emailPreview : undefined, readOnly: useAutoGeneratedLogin }), useAutoGeneratedLogin && emailPreview && (_jsx("p", { className: "mt-1 text-xs text-slate-500 dark:text-slate-400", children: "Preview: Actual employee number will be assigned upon creation" }))] }), _jsxs("div", { children: [_jsxs("label", { className: "mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200", children: [t('department'), " *"] }), _jsxs("select", { className: "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100", ...register('department', { required: true }), children: [_jsx("option", { value: "", children: t('selectDepartment') }), _jsx("option", { value: "operations", children: t('operations') }), _jsx("option", { value: "maintenance", children: t('maintenance') }), _jsx("option", { value: "quality", children: t('quality') }), _jsx("option", { value: "administration", children: t('administration') })] })] }), _jsxs("div", { children: [_jsxs("label", { className: "mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200", children: [t('jobTitle'), " *"] }), _jsxs("select", { className: "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100", ...register('jobTitle', { required: true }), children: [_jsx("option", { value: "", children: t('selectJobTitle') }), _jsx("option", { value: "technician", children: "Technician" }), _jsx("option", { value: "operator", children: "Operator" }), _jsx("option", { value: "supervisor", children: "Supervisor" }), _jsx("option", { value: "manager", children: "Manager" })] })] }), _jsxs("div", { children: [_jsxs("label", { className: "mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200", children: [t('initialRole'), " *"] }), _jsxs("select", { className: "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100", ...register('role', { required: true }), children: [_jsx("option", { value: "employee", children: t('employee') }), _jsx("option", { value: "supervisor", children: t('supervisor') }), _jsx("option", { value: "manager", children: t('manager') }), _jsx("option", { value: "admin", children: t('admin') }), _jsx("option", { value: "global_admin", children: t('globalAdmin') })] })] }), _jsxs("div", { children: [_jsxs("label", { className: "mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200", children: [t('assignedSupervisor'), " *"] }), _jsxs("select", { className: "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100", ...register('supervisorId'), children: [_jsx("option", { value: "", children: t('selectSupervisor') }), supervisors.map((sup) => (_jsx("option", { value: sup.id, children: sup.full_name || sup.fullName }, sup.id)))] }), _jsx("p", { className: "mt-1 text-xs text-slate-500 dark:text-slate-400", children: t('selectSupervisorDesc') })] }), _jsxs("div", { children: [_jsx("label", { className: "mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200", children: "Joined Date" }), _jsx("input", { type: "date", className: "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100", ...register('joinedDate') }), _jsx("p", { className: "mt-1 text-xs text-slate-500 dark:text-slate-400", children: "Employee's start date (only Global Admin can edit)" })] })] }), _jsxs("div", { children: [_jsx("label", { className: "mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200", children: t('personalMessage') }), _jsx("textarea", { rows: 3, className: "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100", ...register('personalMessage'), placeholder: t('addPersonalWelcome') })] }), _jsxs("div", { className: "rounded-xl border border-amber-200 bg-amber-50 p-4 dark:border-amber-500/40 dark:bg-amber-500/10", children: [_jsxs("p", { className: "text-sm font-semibold text-amber-900 dark:text-amber-100", children: ["\u26A0\uFE0F ", t('important')] }), _jsx("p", { className: "mt-1 text-xs text-amber-700 dark:text-amber-200", children: t('credentialsSharedManually') })] }), _jsxs("div", { className: "rounded-xl border border-emerald-200 bg-emerald-50 p-4 dark:border-emerald-500/40 dark:bg-emerald-500/10", children: [_jsxs("p", { className: "text-sm font-semibold text-emerald-900 dark:text-emerald-100", children: ["\uD83C\uDF93 ", t('autoEnrollment')] }), _jsx("p", { className: "mt-1 text-xs text-emerald-700 dark:text-emerald-200", children: t('autoEnrollmentDesc') })] }), _jsxs("div", { className: "flex items-center justify-end gap-3 border-t border-slate-200 pt-4 dark:border-slate-700", children: [_jsx("button", { type: "button", onClick: () => {
                                        setInviteOpen(false);
                                        reset();
                                    }, className: "rounded-xl border border-slate-200 px-4 py-2 text-sm font-medium text-slate-600 hover:border-primary hover:text-primary dark:border-slate-700 dark:text-slate-300", children: t('cancel') }), _jsx("button", { type: "submit", className: "rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-primary/90", children: t('createEmployeeBtn') })] })] }) }), _jsx(Modal, { open: isImportOpen, onClose: () => {
                    setImportOpen(false);
                    setCsvFile(null);
                }, title: t('bulkUserImport'), description: t('importMultipleUsers'), children: _jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "rounded-xl border border-blue-200 bg-blue-50 p-4 dark:border-blue-500/40 dark:bg-blue-500/10", children: [_jsxs("p", { className: "text-sm font-semibold text-blue-900 dark:text-blue-100", children: ["\uD83D\uDCCB ", t('csvFormatRequirements')] }), _jsxs("ul", { className: "mt-2 space-y-1 text-xs text-blue-700 dark:text-blue-200", children: [_jsxs("li", { children: ["\u2022 ", t('requiredColumns')] }), _jsxs("li", { children: ["\u2022 ", t('optionalColumns')] }), _jsxs("li", { children: ["\u2022 ", t('employeeIdAutoGenerated')] }), _jsxs("li", { children: ["\u2022 ", t('supervisorEmailRequired')] }), _jsxs("li", { children: ["\u2022 ", t('noEmailProvided')] })] })] }), _jsxs("button", { className: "inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700 transition hover:border-primary hover:text-primary dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300", children: [_jsx(ArrowDownTrayIcon, { className: "h-5 w-5" }), t('downloadTemplate')] }), _jsxs("div", { children: [_jsx("p", { className: "mb-3 text-sm font-semibold text-slate-900 dark:text-white", children: t('uploadCSVFile') }), _jsxs("label", { className: "flex cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 p-12 transition hover:border-primary hover:bg-slate-100 dark:border-slate-700 dark:bg-slate-800 dark:hover:border-primary dark:hover:bg-slate-700", children: [_jsx(DocumentArrowUpIcon, { className: "h-12 w-12 text-slate-400 dark:text-slate-500" }), _jsx("p", { className: "mt-3 text-sm font-medium text-slate-700 dark:text-slate-300", children: csvFile ? csvFile.name : t('clickToBrowse') }), _jsx("p", { className: "mt-1 text-xs text-slate-500 dark:text-slate-400", children: t('chooseFile') }), _jsx("input", { type: "file", accept: ".csv", onChange: handleCSVUpload, className: "hidden" })] })] }), _jsxs("div", { className: "flex items-center justify-end gap-3 border-t border-slate-200 pt-4 dark:border-slate-700", children: [_jsx("button", { type: "button", onClick: () => {
                                        setImportOpen(false);
                                        setCsvFile(null);
                                    }, className: "rounded-xl border border-slate-200 px-4 py-2 text-sm font-medium text-slate-600 hover:border-primary hover:text-primary dark:border-slate-700 dark:text-slate-300", children: t('cancel') }), _jsx("button", { onClick: handleImport, disabled: !csvFile, className: "rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-primary/90 disabled:opacity-50", children: t('bulkUserImport') })] })] }) }), createdEmployee && (_jsx(EmployeeInfoModal, { open: isEmployeeInfoOpen, onClose: () => {
                    setEmployeeInfoOpen(false);
                    setCreatedEmployee(null);
                }, employeeData: {
                    fullName: createdEmployee.fullName,
                    employeeId: createdEmployee.employeeId,
                    email: createdEmployee.loginIdentifier,
                    department: createdEmployee.department,
                    jobTitle: createdEmployee.jobTitle,
                    role: createdEmployee.role,
                    temporaryPassword: createdEmployee.temporaryPassword
                } })), _jsx(Modal, { open: isEditOpen, onClose: () => {
                    setEditOpen(false);
                    setEditingUser(null);
                    reset();
                }, title: t('editUser') || 'Edit User', description: t('updateUserDetails') || 'Update user details and permissions', children: _jsxs("form", { onSubmit: handleSubmit(handleUpdate), className: "space-y-6", children: [_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "rounded-lg border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-800", children: [_jsxs("label", { className: "flex items-center gap-2", children: [_jsx("input", { type: "checkbox", ...register('useAutoGeneratedLogin'), className: "h-4 w-4 rounded border-slate-300 text-primary focus:ring-primary dark:border-slate-600 dark:bg-slate-700" }), _jsx("span", { className: "text-sm font-medium text-slate-700 dark:text-slate-200", children: t('workerWithoutEmail') })] }), _jsx("p", { className: "mt-2 text-xs text-slate-500 dark:text-slate-400", children: t('autoGeneratedLoginDesc') })] }), _jsxs("div", { children: [_jsxs("label", { className: "mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200", children: [t('fullName'), " *"] }), _jsx("input", { type: "text", ...register('fullName', { required: true }), className: "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100" })] }), !useAutoGeneratedLogin && (_jsxs("div", { children: [_jsxs("label", { className: "mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200", children: [t('emailAddress'), " *"] }), _jsx("input", { type: "email", ...register('email', { required: !useAutoGeneratedLogin }), className: "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100" })] })), _jsxs("div", { children: [_jsxs("label", { className: "mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200", children: [t('department'), " *"] }), _jsxs("select", { className: "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100", ...register('department', { required: true }), children: [_jsx("option", { value: "", children: t('selectDepartment') }), _jsx("option", { value: "operations", children: "Operations" }), _jsx("option", { value: "maintenance", children: "Maintenance" }), _jsx("option", { value: "quality", children: "Quality Control" }), _jsx("option", { value: "administration", children: "Administration" })] })] }), _jsxs("div", { children: [_jsxs("label", { className: "mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200", children: [t('jobTitle'), " *"] }), _jsxs("select", { className: "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100", ...register('jobTitle', { required: true }), children: [_jsx("option", { value: "", children: t('selectJobTitle') }), _jsx("option", { value: "technician", children: "Technician" }), _jsx("option", { value: "operator", children: "Operator" }), _jsx("option", { value: "supervisor", children: "Supervisor" }), _jsx("option", { value: "manager", children: "Manager" })] })] }), _jsxs("div", { children: [_jsxs("label", { className: "mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200", children: [t('initialRole'), " *"] }), _jsxs("select", { className: "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100", ...register('role', { required: true }), children: [_jsx("option", { value: "employee", children: t('employee') }), _jsx("option", { value: "supervisor", children: t('supervisor') }), _jsx("option", { value: "manager", children: t('manager') }), _jsx("option", { value: "admin", children: t('admin') }), _jsx("option", { value: "global_admin", children: t('globalAdmin') })] })] }), _jsxs("div", { children: [_jsxs("label", { className: "mb-2 block text-sm font-medium text-slate-700 dark:text-slate-200", children: [t('assignedSupervisor'), " *"] }), _jsxs("select", { className: "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100", ...register('supervisorId'), children: [_jsx("option", { value: "", children: t('selectSupervisor') }), supervisors.map((sup) => (_jsx("option", { value: sup.id, children: sup.full_name || sup.fullName }, sup.id)))] }), _jsx("p", { className: "mt-1 text-xs text-slate-500 dark:text-slate-400", children: t('selectSupervisorDesc') })] })] }), _jsxs("div", { className: "flex items-center justify-end gap-3 border-t border-slate-200 pt-4 dark:border-slate-700", children: [_jsx("button", { type: "button", onClick: () => {
                                        setEditOpen(false);
                                        setEditingUser(null);
                                        reset();
                                    }, className: "rounded-xl border border-slate-200 px-4 py-2 text-sm font-medium text-slate-600 hover:border-primary hover:text-primary dark:border-slate-700 dark:text-slate-300", children: t('cancel') }), _jsx("button", { type: "submit", className: "rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-primary/90", children: t('updateUser') || 'Update User' })] })] }) })] }));
}
